# Generated by Django 5.1.1 on 2024-09-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validade', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrada', models.DateField()),
                ('nro_nota', models.CharField(max_length=100)),
                ('nome_fornecedor', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AlimentoVencido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validade_venc', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrada', models.DateField()),
                ('nro_nota', models.CharField(max_length=100)),
                ('nome_fornecedor', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=100)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_vencidos', to='estoque.alimento')),
            ],
        ),
        migrations.CreateModel(
            name='AlimentoDevolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validade', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrada', models.DateField()),
                ('nro_nota', models.CharField(max_length=100)),
                ('nome_fornecedor', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=100)),
                ('categoria_dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_devolvidos', to='estoque.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='alimento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='estoque.categoria'),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validade', models.DateField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='estoque.alimento')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaDevolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validade', models.DateField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_devolucao', to='estoque.alimento')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validade', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrada', models.DateField()),
                ('nro_nota', models.CharField(max_length=100)),
                ('nome_fornecedor', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=100)),
                ('alimento_devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='estoque.alimentodevolucao')),
                ('categoria_etiq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='estoque.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validade', models.DateField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='estoque.alimento')),
            ],
        ),
        migrations.CreateModel(
            name='SaidaDevolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validade', models.DateField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas_devolucao', to='estoque.alimento')),
            ],
        ),
    ]
