# Generated by Django 5.1.1 on 2024-10-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiqueta',
            name='alimento_devolucao',
        ),
        migrations.RemoveField(
            model_name='alimentovencido',
            name='alimento',
        ),
        migrations.RemoveField(
            model_name='entradadevolucao',
            name='alimento',
        ),
        migrations.RemoveField(
            model_name='etiqueta',
            name='categoria_etiq',
        ),
        migrations.RemoveField(
            model_name='saidadevolucao',
            name='alimento',
        ),
        migrations.DeleteModel(
            name='AlimentoDevolucao',
        ),
        migrations.DeleteModel(
            name='AlimentoVencido',
        ),
        migrations.DeleteModel(
            name='EntradaDevolucao',
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
        migrations.DeleteModel(
            name='SaidaDevolucao',
        ),
    ]
