# Generated by Django 5.1.1 on 2024-10-27 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_remove_etiqueta_alimento_devolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='saida',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
